import Head from "next/head";
import localFont from "next/font/local";

export default function Home() {
	return (
		<>
			<Head>
				<title>kley.</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="img/logo.png" />
			</Head>
			<div>kley.</div>
		</>
	);
}
